package org.cap1.model;

// Generated Mar 1, 2015 2:09:19 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TransactionToCategory generated by hbm2java
 */
@Entity
@Table(name = "Transaction_To_Category", catalog = "cap1")
public class TransactionToCategory implements java.io.Serializable {

    private Integer id;
    private int categoryId;
    private int transactionId;

    public TransactionToCategory() {
    }

    public TransactionToCategory(int categoryId, int transactionId) {
        this.categoryId = categoryId;
        this.transactionId = transactionId;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "categoryId", nullable = false)
    public int getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    @Column(name = "transactionId", nullable = false)
    public int getTransactionId() {
        return this.transactionId;
    }

    public void setTransactionId(int transactionId) {
        this.transactionId = transactionId;
    }

}
