package org.cap1.model;

// Generated Mar 1, 2015 2:09:19 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TransactionToTag generated by hbm2java
 */
@Entity
@Table(name = "Transaction_To_Tag", catalog = "cap1")
public class TransactionToTag implements java.io.Serializable {

    private Integer id;
    private int tagId;
    private int transactionId;

    public TransactionToTag() {
    }

    public TransactionToTag(int tagId, int transactionId) {
        this.tagId = tagId;
        this.transactionId = transactionId;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "tagId", nullable = false)
    public int getTagId() {
        return this.tagId;
    }

    public void setTagId(int tagId) {
        this.tagId = tagId;
    }

    @Column(name = "transactionId", nullable = false)
    public int getTransactionId() {
        return this.transactionId;
    }

    public void setTransactionId(int transactionId) {
        this.transactionId = transactionId;
    }

}
